<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="FluentAssertions.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Askstatus.Application\Askstatus.Application.csproj" />
    <ProjectReference Include="..\Askstatus.Common\Askstatus.Common.csproj" />
    <ProjectReference Include="..\Askstatus.Domain\Askstatus.Domain.csproj" />
    <ProjectReference Include="..\Askstatus.Infrastructure\Askstatus.Infrastructure.csproj" />
    <ProjectReference Include="..\Askstatus.Sdk\Askstatus.Sdk.csproj" />
    <ProjectReference Include="..\Askstatus.Web.API\Askstatus.Web.API.csproj" />
    <ProjectReference Include="..\Askstatus.Web.App\Askstatus.Web.App.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
