# see https://mosquitto.org/man/mosquitto-conf-5.html

user root
log_dest stdout
allow_anonymous true

log_type error
log_type warning
log_type notice
log_type information

log_timestamp_format %Y-%m-%d %H:%M:%S

# /data is not mounted into the container, so persistence cannot be written.
persistence false

listener 1883
protocol mqtt

sys_interval 1