@Askstatus.Web.API_HostAddress = https://localhost:7298
@ip=192.168.1.85
@id=3
@onoff=False

GET {{Askstatus.Web.API_HostAddress}}/api/weatherforecast/
Accept: application/json

###

POST {{Askstatus.Web.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "userName": "admin",
  "password": "Password123!"
}
###

POST {{Askstatus.Web.API_HostAddress}}/api/identity/logout

###

GET {{Askstatus.Web.API_HostAddress}}/api/identity/userinfo

###

GET {{Askstatus.Web.API_HostAddress}}/api/identity/claims

###

GET {{Askstatus.Web.API_HostAddress}}/api/role

###

POST {{Askstatus.Web.API_HostAddress}}/api/roles

###

GET {{Askstatus.Web.API_HostAddress}}/api/role/permissions

###

GET {{Askstatus.Web.API_HostAddress}}/api/devicediscover?ip={{ip}}

###

GET {{Askstatus.Web.API_HostAddress}}/api/powerdevice

###

POST {{Askstatus.Web.API_HostAddress}}/api/powerdevice
Content-Type: application/json

{
  //PowerDeviceRequest
}

###

PUT {{Askstatus.Web.API_HostAddress}}/api/powerdevice
Content-Type: application/json

{
  //PowerDeviceRequest
}

###

DELETE {{Askstatus.Web.API_HostAddress}}/api/powerdevice/{{id}}

###

GET {{Askstatus.Web.API_HostAddress}}/api/powerdevice/{{id}}

###

GET {{Askstatus.Web.API_HostAddress}}/api/powerdevice/{{id}}/state

###

GET {{Askstatus.Web.API_HostAddress}}/api/powerdevice/{{id}}/switch/{{onoff}}

###

GET {{Askstatus.Web.API_HostAddress}}/api/powerdevice/{{id}}/toggle

###
