@Askstatus.Web.API_HostAddress = https://localhost:7298

GET {{Askstatus.Web.API_HostAddress}}/api/weatherforecast/
Accept: application/json

###

POST {{Askstatus.Web.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "userName": "admin",
  "password": "Password123!"
}
###

POST {{Askstatus.Web.API_HostAddress}}/api/identity/logout

###

GET {{Askstatus.Web.API_HostAddress}}/api/identity/userinfo

###

GET {{Askstatus.Web.API_HostAddress}}/api/identity/claims

###
