# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: >
        dotnet test --no-build
        --ignore-exit-code 8
        --report-trx
        --coverage --coverage-output-format cobertura
        --results-directory TestResults

    - name: Test Report
      uses: dorny/test-reporter@v3
      if: ${{ always() }}
      with:
        name: test-results
        report-title: "Test Results"
        path: "TestResults/**/*.trx"
        reporter: dotnet-trx
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Coverage Report
      uses: danielpalme/ReportGenerator-GitHub-Action@5
      with:
        reports: "TestResults/*.cobertura.xml"
        targetdir: "CoverageReport"
        reporttypes: "MarkdownSummaryGithub;JsonSummary"

    - name: Get Coverage Percentage
      id: extract_coverage
      run: |
        COVERAGE=$(jq '.summary.linecoverage' CoverageReport/Summary.json)
        echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT

    - name: Update Dynamic Badge Gist
      if: github.ref == 'refs/heads/main'
      uses: schneegans/dynamic-badges-action@v1.9.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: cdc4aa1ab92257ffc13f5ae206804c51
        filename: coverage.json
        label: code coverage
        message: ${{ steps.extract_coverage.outputs.percentage }}%
        valColorRange: ${{ steps.extract_coverage.outputs.percentage }}
        maxColorRange: 100
        minColorRange: 0

    - name: Publish coverage in build summary # Only applicable if 'MarkdownSummaryGithub' or one of the other Markdown report types is generated
      run: cat CoverageReport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY # Adjust path and filename if necessary
      shell: bash